[phases.setup]
nixPkgs = ['php83']

[phases.build]
cmds = [
  'composer update --no-dev --optimize-autoloader --no-interaction',
  'php artisan config:cache',
  'php artisan route:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'